services:

  nutriheal-app:

    build:
      context: .
      dockerfile: Dockerfile

    image: nutriheal-app:latest

    container_name: nutriheal-app

    env_file:
      - .env

    ports:
      - "8080:8080"